version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: todo
    networks:
      - my-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

  php:
    build: .
    container_name: php-container
    depends_on:
      - mysql
    networks:
      - my-network
    ports:
      - "80:80"

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
